# Generated by Django 5.1.7 on 2026-05-13 17:15

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('activity_type', models.CharField(choices=[('trekking', 'Trekking / Hiking'), ('water_sports', 'Water Sports'), ('cultural', 'Cultural Experience'), ('wildlife', 'Wildlife & Nature'), ('adventure', 'Adventure Sports'), ('wellness', 'Wellness / Spa'), ('food_tour', 'Food Tour'), ('city_tour', 'City Tour'), ('day_trip', 'Day Trip')], max_length=20)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='easy', max_length=15)),
                ('budget_tier', models.CharField(choices=[('budget', 'Budget'), ('mid', 'Mid-range'), ('premium', 'Premium')], max_length=10)),
                ('approx_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_unit', models.CharField(blank=True, max_length=50)),
                ('duration_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('best_season', models.CharField(blank=True, max_length=100)),
                ('cover_image', models.URLField(blank=True)),
                ('booking_required', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('attraction_type', models.CharField(choices=[('temple', 'Temple / Religious Site'), ('museum', 'Museum'), ('natural_site', 'Natural Site'), ('viewpoint', 'Viewpoint'), ('monument', 'Monument / Historic'), ('market', 'Market / Bazaar'), ('park', 'Park / Garden'), ('beach', 'Beach'), ('waterfall', 'Waterfall'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('cover_image', models.URLField(blank=True)),
                ('budget_tier', models.CharField(blank=True, choices=[('budget', 'Budget'), ('mid', 'Mid-range'), ('premium', 'Premium')], max_length=10)),
                ('avg_duration_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('best_time_of_day', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('anytime', 'Anytime')], default='anytime', max_length=15)),
                ('entrance_fee_required', models.BooleanField(default=False)),
                ('approx_entrance_fee', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.attraction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('cuisine_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('ingredients_note', models.TextField(blank=True)),
                ('spice_level', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot'), ('very_hot', 'Very Hot')], default='mild', max_length=10)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack / Street Food'), ('dessert', 'Dessert'), ('drink', 'Drink / Beverage'), ('any', 'Any')], default='any', max_length=15)),
                ('cover_image', models.URLField(blank=True)),
                ('is_vegetarian_friendly', models.BooleanField(default=False)),
                ('is_must_try', models.BooleanField(db_index=True, default=False)),
                ('approx_price_range', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_must_try', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CuisineImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.cuisine')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('destination_type', models.CharField(choices=[('city', 'City'), ('beach', 'Beach'), ('mountain', 'Mountain'), ('cultural', 'Cultural'), ('nature', 'Nature'), ('island', 'Island'), ('village', 'Village')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tagline', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('cover_image', models.URLField()),
                ('min_stay_days', models.PositiveSmallIntegerField(default=2)),
                ('max_stay_days', models.PositiveSmallIntegerField(default=7)),
                ('budget_tier', models.CharField(choices=[('budget', 'Budget'), ('mid', 'Mid-range'), ('premium', 'Premium')], max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='easy', max_length=15)),
                ('local_languages', models.JSONField(default=list)),
                ('best_travel_months', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]), blank=True, default=list, help_text='Best months to visit as integers from 1 (Jan) to 12 (Dec).', size=None)),
                ('currency', models.CharField(max_length=50)),
                ('currency_code', models.CharField(max_length=3)),
                ('getting_around', models.TextField(blank=True)),
                ('visa_notes', models.TextField(blank=True)),
                ('cultural_tips', models.JSONField(blank=True, default=list, help_text='Simple list of cultural tips for this destination.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=15)),
                ('data_source', models.CharField(choices=[('manual', 'Manual'), ('crawler', 'Crawler'), ('hybrid', 'Hybrid')], default='manual', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cuisine',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='activity',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destination'),
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.destination')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DestinationTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('category', models.CharField(choices=[('experience', 'Experience'), ('vibe', 'Vibe'), ('activity', 'Activity')], max_length=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='destinations.destinationtag'),
        ),
        migrations.AlterUniqueTogether(
            name='cuisine',
            unique_together={('destination', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='attraction',
            unique_together={('destination', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('destination', 'slug')},
        ),
        migrations.AddIndex(
            model_name='destination',
            index=django.contrib.postgres.indexes.GinIndex(fields=['best_travel_months'], name='destination_best_tr_393353_gin'),
        ),
    ]
