# Generated by Django 5.1.7 on 2026-06-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_saveddestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='how_to_reach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='picking_reason_list',
            field=models.JSONField(blank=True, default=list, help_text='List for picking this attractions.'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='attractions', to='destinations.destinationtag'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='tip_list',
            field=models.JSONField(blank=True, default=list, help_text='List for picking this attractions.'),
        ),
    ]
