# Generated by Django 5.1.7 on 2026-06-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_attraction_how_to_reach_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuisine',
            options={'ordering': ['-is_featured', 'name']},
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='picking_reason_list',
            new_name='picking_reasons',
        ),
        migrations.RenameField(
            model_name='cuisine',
            old_name='is_must_try',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='overview',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='difficulty',
            new_name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='cost_unit',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='tip_list',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='approx_price_range',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='ingredients_note',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='cultural_tips',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='data_source',
        ),
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.JSONField(blank=True, default=list, help_text='List of important notes'),
        ),
        migrations.AddField(
            model_name='activity',
            name='picking_reasons',
            field=models.JSONField(blank=True, default=list, help_text='List for picking this attractions.'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='notes',
            field=models.JSONField(blank=True, default=list, help_text='List of important notes'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='approx_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='notes',
            field=models.JSONField(blank=True, default=list, help_text='List of important notes'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='picking_reasons',
            field=models.JSONField(blank=True, default=list, help_text='List for picking this attractions.'),
        ),
        migrations.AddField(
            model_name='destination',
            name='notes',
            field=models.JSONField(blank=True, default=list, help_text='List of important notes'),
        ),
        migrations.AddField(
            model_name='destination',
            name='picking_reasons',
            field=models.JSONField(blank=True, default=list, help_text='List for picking this attractions.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='approx_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
