# Generated by Django 5.1.7 on 2026-08-15 09:04

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0005_alter_cuisine_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="best_season",
        ),
        migrations.AddField(
            model_name="activity",
            name="best_months",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    validators=[
                        django.core.validators.MinValueValidator(1),
                        django.core.validators.MaxValueValidator(12),
                    ]
                ),
                blank=True,
                default=list,
                help_text="Best months to visit as integers from 1 (Jan) to 12 (Dec).",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="attraction",
            name="best_months",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    validators=[
                        django.core.validators.MinValueValidator(1),
                        django.core.validators.MaxValueValidator(12),
                    ]
                ),
                blank=True,
                default=list,
                help_text="Best months to visit as integers from 1 (Jan) to 12 (Dec).",
                size=None,
            ),
        ),
    ]
