# Generated by Codex on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatmessage",
            name="unique_chat_message_sequence",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="payload",
            new_name="metadata",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="sequence",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("agent", "Agent"),
                    ("system", "System"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["created_at"]},
        ),
    ]
