# Generated by Codex on 2026-06-03

from django.db import migrations, models


def migrate_old_profile_preferences(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    for profile in UserProfile.objects.all().only("pk", "travel_style", "accessibility_needs"):
        updates = {}
        if profile.travel_style:
            updates["travel_pace"] = str(profile.travel_style).lower()
        if profile.accessibility_needs:
            updates["mobility_constraints"] = [
                item.strip()
                for item in str(profile.accessibility_needs).splitlines()
                if item.strip()
            ]
        if updates:
            UserProfile.objects.filter(pk=profile.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_username_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mobility_constraints",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="travel_pace",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.RunPython(migrate_old_profile_preferences, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="userprofile",
            name="accessibility_needs",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="travel_style",
        ),
    ]
