# Generated by Django 5.1.7 on 2026-06-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_travel_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_id_token',
            field=models.TextField(blank=True, verbose_name='Firebase ID token'),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Firebase UID'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.TextField(blank=True, verbose_name='Google access token'),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('password', 'Password'), ('google', 'Google')], default='password', max_length=20, verbose_name='Auth provider'),
        ),
    ]
