# Generated by Django 5.1.7 on 2026-08-04 07:07

import app.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_backfill_user_profile_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone used for trip reminders, for example Asia/Dhaka.', max_length=64, validators=[app.base.validators.validate_timezone_name]),
        ),
    ]
