# Generated by Django 5.1.7 on 2026-08-05 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User credit',
                'verbose_name_plural': 'User credits',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('initial_grant', 'Initial grant'), ('monthly_reward', 'Monthly reward'), ('trip_plan', 'Trip plan'), ('trip_chat', 'Trip chat'), ('agent_chat', 'Agent chat'), ('refund', 'Refund'), ('admin_adjustment', 'Admin adjustment')], max_length=30)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.usercredit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', '-created_at'], name='accounts_cr_account_3db69b_idx'), models.Index(fields=['transaction_type', '-created_at'], name='accounts_cr_transac_397811_idx')],
            },
        ),
    ]
