# Generated by Django 5.1.7 on 2026-08-08

import app.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_usercredit_credittransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                validators=[app.base.validators.validate_bio_word_count],
            ),
        ),
    ]
