# Generated by Django 5.1.7 on 2026-08-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_creditrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_tracked_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
