# Generated by Django 5.1.7 on 2026-08-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_last_tracked_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_accommodation',
            field=models.CharField(blank=True, default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(blank=True, default='USD', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(blank=True, default='en', max_length=50),
        ),
    ]
