# Generated by Django 5.1.7 on 2026-06-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vector_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vectordocument',
            new_name='vector_docu_source__b80cad_idx',
            old_name='vector_docu_source__8fdfff_idx',
        ),
        migrations.RenameIndex(
            model_name='vectordocument',
            new_name='vector_docu_metadat_ef9122_gin',
            old_name='vector_docu_metadat_1e173d_gin',
        ),
    ]
