# Generated by Django 5.1.7 on 2026-08-16 10:04

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector_store', '0003_vectordocument_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectordocument',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('content', config='english'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
    ]
