from django.urls import include, path

from destinations.api.v1.client import views

# Endpoints operating on a specific destination instance
destination_specific_patterns = [
    # Core detail & action endpoints
    path("detail/", views.ClientDestinationDetailAPIView.as_view(), name="public-destination-details"),
    path("short-detail/", views.ClientDestinationShortDetailAPIView.as_view(), name="public-destination-short-details"),
    path("save/", views.ClientDestinationSaveAPIView.as_view(), name="public-destination-save"),
    
    # Nested sub-resources (Attractions)
    path("attractions/", views.ClientDestinationAttractionListAPIView.as_view(), name="public-destination-attraction-list"),
    path("attractions/<slug:attraction_slug>/", views.ClientDestinationAttractionDetailAPIView.as_view(), name="public-destination-attraction-detail"),
    
    # Nested sub-resources (Activities)
    path("activities/", views.ClientDestinationActivityListAPIView.as_view(), name="public-destination-activity-list"),
    path("activities/<slug:activity_slug>/", views.ClientDestinationActivityDetailAPIView.as_view(), name="public-destination-activity-detail"),
    
    # Nested sub-resources (Cuisines)
    path("cuisines/", views.ClientDestinationCuisineListAPIView.as_view(), name="public-destination-cuisine-list"),
    path("cuisines/<slug:cuisine_slug>/", views.ClientDestinationCuisineDetailAPIView.as_view(), name="public-destination-cuisine-detail"),
]

urlpatterns = [
    # Top-level collection & general endpoints
    path("list/", views.ClientDestinationListAPIView.as_view(), name="public-destination-list"),
    path("tags/", views.ClientDestinationTagListAPIView.as_view(), name="public-destination-tag-list"),
    path("save/list/", views.ClientSavedDestinationListAPIView.as_view(), name="public-saved-destination-list"),
    path("autogenerated-message/", views.AutogeneratedMessageAPIView.as_view(), name="public-pickup-message"),
    
    # Instance-level endpoints grouped under <slug:slug>/
    path("<slug:slug>/", include(destination_specific_patterns)),
]