import random

from rest_framework.generics import GenericAPIView
from django.db.models import BooleanField, Exists, OuterRef, Prefetch, Q, Value
from django.shortcuts import get_object_or_404
from django.utils import timezone
from rest_framework import status
from rest_framework.permissions import IsAuthenticated

from app.base.pagination import CustomPagination
from app.utils.response import APIResponse
from destinations.api.v1.client.serializers import (
    ClientActivitySerializer,
    ClientAttractionSerializer,
    ClientCuisineSerializer,
    ClientDestinationDetailSerializer,
    ClientDestinationListSerializer,
    ClientDestinationShortDetailSerializer,
    DestinationTagListSerializer,
    DestinationSaveSerializer,
)
from destinations.api.v1.query import (
    apply_activity_filters,
    apply_attraction_filters,
    apply_cuisine_filters,
    apply_destination_filters,
)
from destinations.models import (
    Activity,
    Attraction,
    Cuisine,
    Destination,
    DestinationTag,
    SavedDestination,
)


class DestinationPaginationMixin:
    pagination_class = CustomPagination

    def paginate_with_meta(self, queryset, serializer_class, *, message="Destinations fetched successfully."):
        paginator = self.pagination_class()
        page = paginator.paginate_queryset(queryset, self.request, view=self)
        serializer = serializer_class(page, many=True, context={"request": self.request})
        return APIResponse.success(
            data=serializer.data,
            meta={
                "count": paginator.page.paginator.count,
                "page": paginator.page.number,
                "page_size": paginator.get_page_size(self.request),
                "num_pages": paginator.page.paginator.num_pages,
                "next": paginator.get_next_link(),
                "previous": paginator.get_previous_link(),
            },
            message=message,
        )

    def with_is_saved(self, queryset):
        user = self.request.user
        if not user.is_authenticated:
            return queryset.annotate(is_saved=Value(False, output_field=BooleanField()))
        return queryset.annotate(
            is_saved=Exists(
                SavedDestination.objects.filter(
                    user=user,
                    destination=OuterRef("pk"),
                )
            )
        )


class ClientDestinationListAPIView(DestinationPaginationMixin, GenericAPIView):
    """
    Client destination list API.

    Frontend request:
    - Method: GET
    - Query params:
      `page`, `page_size`
      `search=beach`
      `destination_type=beach,island`
      `country_code=IDN,THA`
      `budget_tier=budget,mid`
      `difficulty=easy`
      `tag=family,romantic`
      `best_travel_month=11,12`
      `region=Southeast Asia`
    - Multiple filters can be combined together.
    - Only published destinations are returned to clients.

    Frontend response:
    - 200 success with paginated destination rows.
    - Each row uses `slug` instead of `id`.
    """

    def get_queryset(self):
        queryset = (
            Destination.objects.filter(status="published")
            .prefetch_related("tags")
            .order_by("name")
        )
        queryset = self.with_is_saved(queryset)
        return apply_destination_filters(queryset, self.request.query_params, include_status=False)

    def get(self, request, *args, **kwargs):
        return self.paginate_with_meta(self.get_queryset(), ClientDestinationListSerializer)


class ClientDestinationTagListAPIView(GenericAPIView):
    """Return the complete destination tag vocabulary without pagination."""

    serializer_class = DestinationTagListSerializer

    def get_queryset(self):
        queryset = DestinationTag.objects.all().order_by("name", "id")
        search = self.request.query_params.get("search", "").strip()
        name = self.request.query_params.get("name", "").strip()
        categories = [
            value.strip()
            for value in self.request.query_params.get("category", "").split(",")
            if value.strip()
        ]

        if search:
            queryset = queryset.filter(
                Q(name__icontains=search) | Q(category__icontains=search)
            )
        if name:
            queryset = queryset.filter(name__icontains=name)
        if categories:
            queryset = queryset.filter(category__in=categories)

        return queryset

    def get(self, request, *args, **kwargs):
        serializer = self.get_serializer(self.get_queryset(), many=True)
        return APIResponse.success(
            data=serializer.data,
            message="Destination tags fetched successfully.",
        )


class AutogeneratedMessageAPIView(DestinationPaginationMixin, GenericAPIView):
    """
    Return one chat-starting prompt based on a random published destination.
    """

    GENERAL_TEMPLATES = (
        "Your next trip might already be calling. Based on your travel vibe, {destination_name} could be perfect right now. Want to explore it?",
        "Need a quick escape idea? From your preferences, {destination_name} feels like a strong match. Want me to help you map it out?",
        "Your travel taste says adventure is overdue. {destination_name} could be the one to try next. Want to take a look?",
        "Not sure where to go next? Based on what you enjoy, {destination_name} could be a beautiful choice for your next plan.",
    )
    BEST_TIME_TEMPLATE = (
        "Looks like a great time to plan something fresh. "
        "{destination_name} is worth visiting in {current_month}. Want to start planning?"
    )
    FALLBACK_MESSAGE = (
        "Not sure where to go next yet? Tell me what kind of trip you want, "
        "and I will help you find a place that fits."
    )

    def get_queryset(self):
        queryset = (
            Destination.objects.filter(status="published")
            .prefetch_related("tags")
            .order_by("name")
        )
        queryset = self.with_is_saved(queryset)
        return apply_destination_filters(queryset, self.request.query_params, include_status=False)

    def get(self, request, *args, **kwargs):
        current_month = timezone.localdate().month
        current_month_name = timezone.localdate().strftime("%B")
        base_queryset = self._apply_user_preferences(self.get_queryset())

        destination = None
        template = random.choice(self.GENERAL_TEMPLATES)
        seasonal_queryset = base_queryset.filter(best_travel_months__overlap=[current_month])

        use_seasonal_prompt = seasonal_queryset.exists() and random.choice([True, False])
        if use_seasonal_prompt:
            destination = self._pick_random_destination(seasonal_queryset)
            template = self.BEST_TIME_TEMPLATE

        if destination is None:
            destination = self._pick_random_destination(base_queryset)

        if destination is None:
            return APIResponse.success(
                data={
                    "message": self.FALLBACK_MESSAGE,
                    "destination_name": "",
                    "destination_slug": "",
                    "is_now_best_time": False,
                },
                message="Autogenerated message fetched successfully.",
            )

        return APIResponse.success(
            data={
                "message": template.format(
                    destination_name=destination.name,
                    current_month=current_month_name,
                ),
                "destination_name": destination.name,
                "destination_slug": destination.slug,
                "is_now_best_time": current_month in destination.best_travel_months,
            },
            message="Autogenerated message fetched successfully.",
        )

    def _pick_random_destination(self, queryset):
        destination_ids = list(queryset.values_list("id", flat=True))
        if not destination_ids:
            return None
        return queryset.get(id=random.choice(destination_ids))

    def _apply_user_preferences(self, queryset):
        user = self.request.user
        if not user.is_authenticated or not hasattr(user, "profile"):
            return queryset

        preferences = self._normalize_preferences(user.profile.travel_interests)
        if not preferences:
            return queryset

        preference_filter = Q()
        destination_type_values = {
            value for value, _label in Destination._meta.get_field("destination_type").choices
        }
        for preference in preferences:
            preference_filter |= Q(tags__name__icontains=preference)
            preference_filter |= Q(tags__slug__icontains=preference)
            preference_filter |= Q(tagline__icontains=preference)
            preference_filter |= Q(description__icontains=preference)
            if preference in destination_type_values:
                preference_filter |= Q(destination_type=preference)

        preferred_queryset = queryset.filter(preference_filter).distinct()
        if preferred_queryset.exists():
            return preferred_queryset
        return queryset

    def _normalize_preferences(self, preferences):
        if not isinstance(preferences, list):
            return []

        normalized_preferences = []
        for preference in preferences:
            if isinstance(preference, dict):
                preference = preference.get("slug") or preference.get("name") or preference.get("value")
            preference = str(preference or "").strip().lower()
            if preference:
                normalized_preferences.append(preference)
        return normalized_preferences


class ClientDestinationDetailAPIView(DestinationPaginationMixin, GenericAPIView):
    """
    Client destination detail API.

    Frontend request:
    - Method: GET
    - URL param: `slug` from the client list API.

    Frontend response:
    - 200 success with the full published destination payload.
    - No internal `id` is exposed to the client.
    """

    def get_object(self):
        queryset = self.with_is_saved(
            Destination.objects.filter(status="published")
            .prefetch_related(
                "tags",
                "images",
                Prefetch(
                    "attractions",
                    queryset=Attraction.objects.prefetch_related("tags"),
                ),
                "activities",
                "cuisines",
            )
        )
        return get_object_or_404(
            queryset,
            slug=self.kwargs["slug"],
        )

    def get(self, request, *args, **kwargs):
        destination = self.get_object()
        return APIResponse.success(
            data=ClientDestinationDetailSerializer(
                destination,
                context={"request": request},
            ).data,
            message="Destination fetched successfully.",
        )


class ClientDestinationShortDetailAPIView(GenericAPIView):
    """
    Client destination short detail API.

    Frontend request:
    - Method: GET
    - URL param: `slug` from the client list API.

    Frontend response:
    - 200 success with name, cover_image, and description for a published destination.
    """

    def get_object(self):
        return get_object_or_404(
            Destination.objects.filter(status="published").prefetch_related("tags"),
            slug=self.kwargs["slug"],
        )

    def get(self, request, *args, **kwargs):
        destination = self.get_object()
        return APIResponse.success(
            data=ClientDestinationShortDetailSerializer(
                destination,
                context={"request": request},
            ).data,
            message="Destination short detail fetched successfully.",
        )


class ClientDestinationChildListAPIView(DestinationPaginationMixin, GenericAPIView):
    """Base client API for a published destination's paginated child resources."""

    model = None
    serializer_class = None
    filter_queryset = None
    resource_label = ""

    def get_destination(self):
        if not hasattr(self, "_destination"):
            self._destination = get_object_or_404(
                Destination.objects.filter(status="published"),
                slug=self.kwargs["slug"],
            )
        return self._destination

    def get_queryset(self):
        queryset = self.model.objects.filter(destination=self.get_destination()).prefetch_related("images")
        return self.filter_queryset(queryset, self.request.query_params)

    def get(self, request, *args, **kwargs):
        return self.paginate_with_meta(
            self.get_queryset(),
            self.serializer_class,
            message=f"{self.resource_label} fetched successfully.",
        )


class ClientDestinationAttractionListAPIView(ClientDestinationChildListAPIView):
    """GET attractions for a destination slug.

    Filters: page, page_size, search, attraction_type, budget_tier,
    best_time_of_day, entrance_fee_required, is_featured.
    """

    model = Attraction
    serializer_class = ClientAttractionSerializer
    filter_queryset = staticmethod(apply_attraction_filters)
    resource_label = "Attractions"


class ClientDestinationActivityListAPIView(ClientDestinationChildListAPIView):
    """GET activities for a destination slug.

    Filters: page, page_size, search, activity_type, budget_tier,
    difficulty_level (or difficulty), booking_required, is_featured.
    """

    model = Activity
    serializer_class = ClientActivitySerializer
    filter_queryset = staticmethod(apply_activity_filters)
    resource_label = "Activities"


class ClientDestinationCuisineListAPIView(ClientDestinationChildListAPIView):
    """GET cuisines for a destination slug.

    Filters: page, page_size, search, cuisine_type, spice_level, meal_type,
    is_vegetarian_friendly (or vegetarian_friendly), is_featured (or featured).
    """

    model = Cuisine
    serializer_class = ClientCuisineSerializer
    filter_queryset = staticmethod(apply_cuisine_filters)
    resource_label = "Cuisines"


class ClientDestinationChildDetailAPIView(GenericAPIView):
    """Base detail API for a child resource belonging to a published destination."""

    model = None
    serializer_class = None
    child_slug_kwarg = ""
    resource_label = ""
    prefetch_fields = ("images",)

    def get_object(self):
        queryset = self.model.objects.filter(
            destination__status="published",
            destination__slug=self.kwargs["slug"],
        ).prefetch_related(*self.prefetch_fields)
        return get_object_or_404(
            queryset,
            slug=self.kwargs[self.child_slug_kwarg],
        )

    def get(self, request, *args, **kwargs):
        return APIResponse.success(
            data=self.serializer_class(
                self.get_object(),
                context={"request": request},
            ).data,
            message=f"{self.resource_label} fetched successfully.",
        )


class ClientDestinationAttractionDetailAPIView(ClientDestinationChildDetailAPIView):
    """GET one attraction by destination slug and attraction slug."""

    model = Attraction
    serializer_class = ClientAttractionSerializer
    child_slug_kwarg = "attraction_slug"
    resource_label = "Attraction"
    prefetch_fields = ("images", "tags")


class ClientDestinationActivityDetailAPIView(ClientDestinationChildDetailAPIView):
    """GET one activity by destination slug and activity slug."""

    model = Activity
    serializer_class = ClientActivitySerializer
    child_slug_kwarg = "activity_slug"
    resource_label = "Activity"


class ClientDestinationCuisineDetailAPIView(ClientDestinationChildDetailAPIView):
    """GET one cuisine by destination slug and cuisine slug."""

    model = Cuisine
    serializer_class = ClientCuisineSerializer
    child_slug_kwarg = "cuisine_slug"
    resource_label = "Cuisine"


class ClientSavedDestinationListAPIView(DestinationPaginationMixin, GenericAPIView):
    """
    User saved destination list API.

    Frontend request:
    - Method: GET
    - Headers: authenticated bearer token
    - Query params: `page`, `page_size`

    Frontend response:
    - 200 success with paginated destination rows saved by the current user.
    """

    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = (
            Destination.objects.filter(
                status="published",
                saved_by_users__user=self.request.user,
            )
            .prefetch_related("tags")
            .order_by("-saved_by_users__created_at")
        )
        return self.with_is_saved(queryset)

    def get(self, request, *args, **kwargs):
        return self.paginate_with_meta(self.get_queryset(), ClientDestinationListSerializer)


class ClientDestinationSaveAPIView(GenericAPIView):
    """
    Save or remove a destination from the authenticated user's saved list.

    Frontend request:
    - Method: POST
    - Headers: authenticated bearer token
    - Body: `{ "save": true }` to save, `{ "save": false }` to remove.

    Frontend response:
    - 200 success with `saved` reflecting the final state.
    """

    permission_classes = [IsAuthenticated]
    serializer_class = DestinationSaveSerializer

    def get_destination(self):
        return get_object_or_404(
            Destination.objects.filter(status="published"),
            slug=self.kwargs["slug"],
        )

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        destination = self.get_destination()
        should_save = serializer.validated_data["save"]

        if should_save:
            SavedDestination.objects.get_or_create(
                user=request.user,
                destination=destination,
                defaults={
                    "created_by": request.user,
                    "updated_by": request.user,
                },
            )
            message = "Destination saved successfully."
        else:
            SavedDestination.objects.filter(
                user=request.user,
                destination=destination,
            ).delete()
            message = "Destination removed from saved list successfully."

        return APIResponse.success(
            data={
                "slug": destination.slug,
                "saved": should_save,
            },
            message=message,
            status=status.HTTP_200_OK,
        )
