# Generated by Django 5.1.7 on 2026-08-09 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journalreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='journalcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('journal', 'Journal'), ('comment', 'Comment')], max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='journals.journalcomment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='journals.journal')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_content_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_journal_content_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'target_type', '-created_at'], name='journals_co_status_c2ca83_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('journal__isnull', False), ('target_type', 'journal')), models.Q(('comment__isnull', False), ('journal__isnull', True), ('target_type', 'comment')), _connector='OR'), name='content_report_has_matching_target'), models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('target_type', 'journal')), fields=('reporter', 'journal'), name='unique_pending_journal_report_per_user'), models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('target_type', 'comment')), fields=('reporter', 'comment'), name='unique_pending_comment_report_per_user')],
            },
        ),
    ]
