# Generated by Django 5.1.7 on 2026-05-13 17:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('share_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('link_only', 'Link Only')], default='private', max_length=15)),
                ('planning_source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('hybrid', 'Hybrid')], default='hybrid', max_length=10)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('nights', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('travelers_count', models.PositiveSmallIntegerField(default=1)),
                ('trip_pace', models.CharField(choices=[('relaxed', 'Relaxed'), ('balanced', 'Balanced'), ('fast', 'Fast')], default='balanced', max_length=10)),
                ('origin_city', models.CharField(blank=True, max_length=120)),
                ('origin_country', models.CharField(blank=True, max_length=120)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Flexible trip preferences collected from the user or AI agent.')),
                ('constraints', models.JSONField(blank=True, default=dict, help_text='Hard constraints such as dates, visa issues, accessibility needs, or dietary rules.')),
                ('traveler_profile_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of relevant user profile data at planning time.')),
                ('planning_summary', models.TextField(blank=True)),
                ('agent_context', models.JSONField(blank=True, default=dict, help_text='Agent-specific structured state, prompts, or planning notes.')),
                ('latest_plan_version', models.PositiveSmallIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TripDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('stay_nights', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('transport_from_previous', models.JSONField(blank=True, default=dict, help_text='Structured transport details from the previous destination.')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_destinations', to='destinations.destination')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_destinations', to='trips.trip')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('trip_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='days', to='trips.tripdestination')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='TripItineraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('transit', 'Transit'), ('attraction', 'Attraction'), ('activity', 'Activity'), ('cuisine', 'Cuisine'), ('hotel', 'Hotel / Stay'), ('food', 'Food'), ('free_time', 'Free Time'), ('note', 'Note'), ('custom', 'Custom')], db_index=True, default='custom', max_length=20)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('planned', 'Planned'), ('booked', 'Booked'), ('completed', 'Completed'), ('skipped', 'Skipped')], db_index=True, default='planned', max_length=15)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('location_name', models.CharField(blank=True, max_length=180)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_currency', models.CharField(blank=True, max_length=10)),
                ('booking_required', models.BooleanField(default=False)),
                ('booking_reference', models.CharField(blank=True, max_length=120)),
                ('external_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible structured details such as transport info, restaurant notes, or AI reasoning.')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_items', to='destinations.activity')),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_items', to='destinations.attraction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_items', to='destinations.cuisine')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.tripday')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='trips.trip')),
                ('trip_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_items', to='trips.tripdestination')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day__day_number', 'sort_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TripPlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('hybrid', 'Hybrid')], default='agent', max_length=10)),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Full structured snapshot of the trip plan at a given version.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_versions', to='trips.trip')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'status'], name='trips_trip_user_id_93e0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'start_date'], name='trips_trip_user_id_03af45_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), ('start_date__isnull', True), _connector='OR'), name='trip_end_date_after_start_date'),
        ),
        migrations.AddIndex(
            model_name='tripdestination',
            index=models.Index(fields=['trip', 'sort_order'], name='trips_tripd_trip_id_bf4058_idx'),
        ),
        migrations.AddIndex(
            model_name='tripdestination',
            index=models.Index(fields=['destination'], name='trips_tripd_destina_3ab5ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripdestination',
            constraint=models.UniqueConstraint(fields=('trip', 'sort_order'), name='unique_trip_destination_order'),
        ),
        migrations.AddConstraint(
            model_name='tripdestination',
            constraint=models.UniqueConstraint(fields=('trip', 'destination', 'sort_order'), name='unique_trip_destination_row'),
        ),
        migrations.AddConstraint(
            model_name='tripdestination',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('trip',), name='unique_primary_destination_per_trip'),
        ),
        migrations.AddConstraint(
            model_name='tripdestination',
            constraint=models.CheckConstraint(condition=models.Q(('departure_date__gte', models.F('arrival_date')), ('departure_date__isnull', True), ('arrival_date__isnull', True), _connector='OR'), name='trip_destination_departure_after_arrival'),
        ),
        migrations.AddIndex(
            model_name='tripday',
            index=models.Index(fields=['trip', 'day_number'], name='trips_tripd_trip_id_c2e586_idx'),
        ),
        migrations.AddIndex(
            model_name='tripday',
            index=models.Index(fields=['trip', 'date'], name='trips_tripd_trip_id_c98ead_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripday',
            constraint=models.UniqueConstraint(fields=('trip', 'day_number'), name='unique_trip_day_number'),
        ),
        migrations.AddConstraint(
            model_name='tripday',
            constraint=models.UniqueConstraint(condition=models.Q(('date__isnull', False)), fields=('trip', 'date'), name='unique_trip_date'),
        ),
        migrations.AddIndex(
            model_name='tripitineraryitem',
            index=models.Index(fields=['trip', 'status'], name='trips_tripi_trip_id_8bf16b_idx'),
        ),
        migrations.AddIndex(
            model_name='tripitineraryitem',
            index=models.Index(fields=['trip', 'item_type'], name='trips_tripi_trip_id_dc0cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='tripitineraryitem',
            index=models.Index(fields=['day', 'sort_order'], name='trips_tripi_day_id_024081_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripitineraryitem',
            constraint=models.UniqueConstraint(fields=('day', 'sort_order'), name='unique_trip_item_order_per_day'),
        ),
        migrations.AddConstraint(
            model_name='tripitineraryitem',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gte', models.F('start_time')), ('end_time__isnull', True), ('start_time__isnull', True), _connector='OR'), name='trip_item_end_time_after_start_time'),
        ),
        migrations.AddIndex(
            model_name='tripplanversion',
            index=models.Index(fields=['trip', 'version'], name='trips_tripp_trip_id_fbafd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripplanversion',
            constraint=models.UniqueConstraint(fields=('trip', 'version'), name='unique_trip_plan_version'),
        ),
    ]
