# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="accommodation_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("budget", "Budget"),
                    ("mid_range", "Mid-range"),
                    ("luxury", "Luxury"),
                    ("boutique", "Boutique"),
                    ("apartment", "Apartment"),
                    ("hostel", "Hostel"),
                    ("any", "Any"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="duration_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="start_location_address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="trip",
            name="start_location_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="start_location_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="traveler_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("solo", "Solo"),
                    ("couple", "Couple"),
                    ("family", "Family"),
                    ("friends", "Friends"),
                    ("group", "Group"),
                    ("business", "Business"),
                ],
                max_length=20,
            ),
        ),
    ]
