# Generated by Codex on 2026-06-03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trip_create_request_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="current_step",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
    ]
