# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_trip_current_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="agent_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trip",
            name="agent_active_failed_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="agent_message",
            field=models.TextField(blank=True),
        ),
    ]
