# Generated by Codex on 2026-06-04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0004_trip_agent_active_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripAgentConversationSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_step",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("external_session_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("qna_count", models.PositiveSmallIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_conversation_sessions",
                        to="trips.trip",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_agent_conversation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TripAgentMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sender", models.CharField(choices=[("user", "User"), ("agent", "Agent")], max_length=10)),
                (
                    "step",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("content", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="trips.tripagentconversationsession",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_messages",
                        to="trips.trip",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tripagentconversationsession",
            index=models.Index(fields=["trip", "current_step", "is_active"], name="trips_tripa_trip_id_5c7bdc_idx"),
        ),
        migrations.AddIndex(
            model_name="tripagentconversationsession",
            index=models.Index(fields=["user", "is_active"], name="trips_tripa_user_id_14f96e_idx"),
        ),
        migrations.AddIndex(
            model_name="tripagentmessage",
            index=models.Index(fields=["trip", "step"], name="trips_tripa_trip_id_be9103_idx"),
        ),
        migrations.AddIndex(
            model_name="tripagentmessage",
            index=models.Index(fields=["session", "sender"], name="trips_tripa_session_7150a3_idx"),
        ),
        migrations.AddConstraint(
            model_name="tripagentmessage",
            constraint=models.UniqueConstraint(fields=("session", "sequence"), name="unique_trip_agent_message_sequence"),
        ),
    ]
