# Generated by Django 5.1.7 on 2026-06-05 23:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_activityimage_caption_attractionimage_caption_and_more'),
        ('trips', '0005_trip_agent_conversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripitineraryitem',
            name='day',
        ),
        migrations.RemoveField(
            model_name='tripitineraryitem',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='tripitineraryitem',
            name='attraction',
        ),
        migrations.RemoveField(
            model_name='tripitineraryitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tripitineraryitem',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='tripitineraryitem',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='tripitineraryitem',
            name='trip_destination',
        ),
        migrations.RemoveField(
            model_name='tripitineraryitem',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tripplanversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tripplanversion',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='tripplanversion',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='agent_message',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='latest_plan_version',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='traveler_profile_snapshot',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_pace',
        ),
        migrations.AddField(
            model_name='trip',
            name='budget_tier',
            field=models.CharField(blank=True, choices=[('backpacker', 'Backpacker'), ('budget', 'Budget'), ('comfort', 'Comfort'), ('premium', 'Premium'), ('luxury', 'Luxury')], max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_itinerary_design_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_qna_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_recommendation_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_trip_preparation_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TripItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_finalized', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_itinerary', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripItineraryBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('food', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activities', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tickets_or_entry', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('miscellaneous', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('itinerary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rough_budget', to='trips.tripitinerary')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TripItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='trips.tripitinerary')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='TripItineraryDayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('title', models.CharField(max_length=180)),
                ('item_id', models.UUIDField(blank=True, null=True)),
                ('item_type', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trip_itinerary_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_items', to='trips.tripitineraryday')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='TripPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_preparation', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripHeadsUpInfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('safety', 'Safety'), ('weather', 'Weather'), ('culture', 'Culture'), ('transport', 'Transport'), ('money', 'Money'), ('health', 'Health'), ('connectivity', 'Connectivity'), ('timing', 'Timing'), ('rules', 'Rules'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('additional_note', models.TextField(blank=True)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads_up', to='trips.trippreparation')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TripPreparationPackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=180)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('toiletries', 'Toiletries'), ('electronics', 'Electronics'), ('medicine', 'Medicine'), ('travel_gear', 'Travel Gear'), ('safety', 'Safety'), ('weather', 'Weather'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('priority', models.CharField(choices=[('essential', 'Essential'), ('recommended', 'Recommended'), ('optional', 'Optional')], db_index=True, default='recommended', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='trips.trippreparation')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TripRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_recommendation_message', models.TextField(blank=True)),
                ('cusine_recommendation_message', models.TextField(blank=True)),
                ('activity_recommendation_message', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_finalized', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_recommendations', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripCuisineRecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_recommendation_items', to='destinations.cuisine')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine_items', to='trips.triprecommendations')),
            ],
        ),
        migrations.CreateModel(
            name='TripAttractionRecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_recommendation_items', to='destinations.attraction')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_items', to='trips.triprecommendations')),
            ],
        ),
        migrations.CreateModel(
            name='TripActivityRecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_recommendation_items', to='destinations.activity')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_items', to='trips.triprecommendations')),
            ],
        ),
        migrations.CreateModel(
            name='TripRequiredDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=180)),
                ('document_url', models.URLField(blank=True)),
                ('document_url_public_id', models.CharField(blank=True, max_length=255)),
                ('required_level', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended'), ('conditional', 'Conditional')], db_index=True, default='recommended', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('additional_note', models.TextField(blank=True)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='trips.trippreparation')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TripRoutePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('to_point', models.CharField(max_length=255)),
                ('from_point', models.CharField(max_length=255)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('transport_mode', models.CharField(max_length=50)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plan_items', to='trips.tripitinerary')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.DeleteModel(
            name='TripDay',
        ),
        migrations.DeleteModel(
            name='TripItineraryItem',
        ),
        migrations.DeleteModel(
            name='TripPlanVersion',
        ),
        migrations.AddIndex(
            model_name='tripitineraryday',
            index=models.Index(fields=['itinerary', 'day'], name='trips_tripi_itinera_d2c1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='tripitineraryday',
            index=models.Index(fields=['itinerary', 'date'], name='trips_tripi_itinera_d05795_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripitineraryday',
            constraint=models.UniqueConstraint(fields=('itinerary', 'day'), name='unique_itinerary_day_order'),
        ),
        migrations.AddIndex(
            model_name='tripitinerarydayitem',
            index=models.Index(fields=['trip_itinerary_day', 'time'], name='trips_tripi_trip_it_1d7aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='tripitinerarydayitem',
            index=models.Index(fields=['item_type'], name='trips_tripi_item_ty_5e3312_idx'),
        ),
        migrations.AddIndex(
            model_name='trippreparation',
            index=models.Index(fields=['trip', 'is_finalized'], name='trips_tripp_trip_id_660ede_idx'),
        ),
        migrations.AddIndex(
            model_name='tripheadsupinfoitem',
            index=models.Index(fields=['preparation', 'sort_order'], name='trips_triph_prepara_f1d11a_idx'),
        ),
        migrations.AddIndex(
            model_name='tripheadsupinfoitem',
            index=models.Index(fields=['category'], name='trips_triph_categor_4b6dff_idx'),
        ),
        migrations.AddIndex(
            model_name='tripheadsupinfoitem',
            index=models.Index(fields=['severity'], name='trips_triph_severit_66ab2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripheadsupinfoitem',
            constraint=models.UniqueConstraint(fields=('preparation', 'sort_order'), name='unique_heads_up_info_order'),
        ),
        migrations.AddIndex(
            model_name='trippreparationpackingitem',
            index=models.Index(fields=['preparation', 'sort_order'], name='trips_tripp_prepara_04573e_idx'),
        ),
        migrations.AddIndex(
            model_name='trippreparationpackingitem',
            index=models.Index(fields=['category'], name='trips_tripp_categor_4f16ef_idx'),
        ),
        migrations.AddIndex(
            model_name='trippreparationpackingitem',
            index=models.Index(fields=['priority'], name='trips_tripp_priorit_59311a_idx'),
        ),
        migrations.AddConstraint(
            model_name='trippreparationpackingitem',
            constraint=models.UniqueConstraint(fields=('preparation', 'sort_order'), name='unique_packing_item_order'),
        ),
        migrations.AddIndex(
            model_name='triprequireddocumentitem',
            index=models.Index(fields=['preparation', 'sort_order'], name='trips_tripr_prepara_cab8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='triprequireddocumentitem',
            index=models.Index(fields=['required_level'], name='trips_tripr_require_471257_idx'),
        ),
        migrations.AddConstraint(
            model_name='triprequireddocumentitem',
            constraint=models.UniqueConstraint(fields=('preparation', 'sort_order'), name='unique_required_document_order'),
        ),
        migrations.AddIndex(
            model_name='triprouteplanitem',
            index=models.Index(fields=['itinerary', 'date', 'start_time'], name='trips_tripr_itinera_f373ed_idx'),
        ),
    ]
