# Generated by Django 5.1.7 on 2026-07-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_tripnote_tripnoteimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='origin_city',
            new_name='origin_cty',
        ),
        migrations.RenameIndex(
            model_name='tripnote',
            new_name='trips_tripn_trip_id_89c8ad_idx',
            old_name='trips_tripn_trip_id_08ea0e_idx',
        ),
    ]
