# Generated by Django 5.1.7 on 2026-07-12 08:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('trips', '0010_rename_origin_cty_trip_origin_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tripheadsupinfoitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripheadsupinfoitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripheadsupinfoitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tripheadsupinfoitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trippreparation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trippreparation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trippreparation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trippreparation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trippreparationpackingitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trippreparationpackingitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trippreparationpackingitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trippreparationpackingitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triprequireddocumentitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triprequireddocumentitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triprequireddocumentitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='triprequireddocumentitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=r"""
                    ALTER TABLE trips_trippreparation ADD COLUMN id_uuid uuid;
                    ALTER TABLE trips_tripheadsupinfoitem ADD COLUMN id_uuid uuid;
                    ALTER TABLE trips_trippreparationpackingitem ADD COLUMN id_uuid uuid;
                    ALTER TABLE trips_triprequireddocumentitem ADD COLUMN id_uuid uuid;

                    ALTER TABLE trips_tripheadsupinfoitem ADD COLUMN preparation_uuid uuid;
                    ALTER TABLE trips_trippreparationpackingitem ADD COLUMN preparation_uuid uuid;
                    ALTER TABLE trips_triprequireddocumentitem ADD COLUMN preparation_uuid uuid;

                    UPDATE trips_trippreparation
                    SET id_uuid = (
                        substr(md5('trips_trippreparation:' || id::text), 1, 8) || '-' ||
                        substr(md5('trips_trippreparation:' || id::text), 9, 4) || '-' ||
                        substr(md5('trips_trippreparation:' || id::text), 13, 4) || '-' ||
                        substr(md5('trips_trippreparation:' || id::text), 17, 4) || '-' ||
                        substr(md5('trips_trippreparation:' || id::text), 21, 12)
                    )::uuid;

                    UPDATE trips_tripheadsupinfoitem
                    SET id_uuid = (
                        substr(md5('trips_tripheadsupinfoitem:' || id::text), 1, 8) || '-' ||
                        substr(md5('trips_tripheadsupinfoitem:' || id::text), 9, 4) || '-' ||
                        substr(md5('trips_tripheadsupinfoitem:' || id::text), 13, 4) || '-' ||
                        substr(md5('trips_tripheadsupinfoitem:' || id::text), 17, 4) || '-' ||
                        substr(md5('trips_tripheadsupinfoitem:' || id::text), 21, 12)
                    )::uuid;

                    UPDATE trips_trippreparationpackingitem
                    SET id_uuid = (
                        substr(md5('trips_trippreparationpackingitem:' || id::text), 1, 8) || '-' ||
                        substr(md5('trips_trippreparationpackingitem:' || id::text), 9, 4) || '-' ||
                        substr(md5('trips_trippreparationpackingitem:' || id::text), 13, 4) || '-' ||
                        substr(md5('trips_trippreparationpackingitem:' || id::text), 17, 4) || '-' ||
                        substr(md5('trips_trippreparationpackingitem:' || id::text), 21, 12)
                    )::uuid;

                    UPDATE trips_triprequireddocumentitem
                    SET id_uuid = (
                        substr(md5('trips_triprequireddocumentitem:' || id::text), 1, 8) || '-' ||
                        substr(md5('trips_triprequireddocumentitem:' || id::text), 9, 4) || '-' ||
                        substr(md5('trips_triprequireddocumentitem:' || id::text), 13, 4) || '-' ||
                        substr(md5('trips_triprequireddocumentitem:' || id::text), 17, 4) || '-' ||
                        substr(md5('trips_triprequireddocumentitem:' || id::text), 21, 12)
                    )::uuid;

                    UPDATE trips_tripheadsupinfoitem item
                    SET preparation_uuid = preparation.id_uuid
                    FROM trips_trippreparation preparation
                    WHERE item.preparation_id = preparation.id;

                    UPDATE trips_trippreparationpackingitem item
                    SET preparation_uuid = preparation.id_uuid
                    FROM trips_trippreparation preparation
                    WHERE item.preparation_id = preparation.id;

                    UPDATE trips_triprequireddocumentitem item
                    SET preparation_uuid = preparation.id_uuid
                    FROM trips_trippreparation preparation
                    WHERE item.preparation_id = preparation.id;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=r"""

                    ALTER TABLE trips_trippreparation ALTER COLUMN id_uuid SET NOT NULL;
                    ALTER TABLE trips_tripheadsupinfoitem ALTER COLUMN id_uuid SET NOT NULL;
                    ALTER TABLE trips_trippreparationpackingitem ALTER COLUMN id_uuid SET NOT NULL;
                    ALTER TABLE trips_triprequireddocumentitem ALTER COLUMN id_uuid SET NOT NULL;
                    ALTER TABLE trips_tripheadsupinfoitem ALTER COLUMN preparation_uuid SET NOT NULL;
                    ALTER TABLE trips_trippreparationpackingitem ALTER COLUMN preparation_uuid SET NOT NULL;
                    ALTER TABLE trips_triprequireddocumentitem ALTER COLUMN preparation_uuid SET NOT NULL;

                    DO $$
                    DECLARE
                        constraint_record record;
                    BEGIN
                        FOR constraint_record IN
                            SELECT conrelid::regclass::text AS table_name, conname
                            FROM pg_constraint
                            WHERE conrelid IN (
                                'trips_tripheadsupinfoitem'::regclass,
                                'trips_trippreparationpackingitem'::regclass,
                                'trips_triprequireddocumentitem'::regclass
                            )
                            AND confrelid = 'trips_trippreparation'::regclass
                        LOOP
                            EXECUTE format(
                                'ALTER TABLE %s DROP CONSTRAINT %I',
                                constraint_record.table_name,
                                constraint_record.conname
                            );
                        END LOOP;
                    END $$;

                    ALTER TABLE trips_tripheadsupinfoitem DROP COLUMN preparation_id CASCADE;
                    ALTER TABLE trips_trippreparationpackingitem DROP COLUMN preparation_id CASCADE;
                    ALTER TABLE trips_triprequireddocumentitem DROP COLUMN preparation_id CASCADE;

                    ALTER TABLE trips_tripheadsupinfoitem DROP CONSTRAINT trips_tripheadsupinfoitem_pkey;
                    ALTER TABLE trips_trippreparationpackingitem DROP CONSTRAINT trips_trippreparationpackingitem_pkey;
                    ALTER TABLE trips_triprequireddocumentitem DROP CONSTRAINT trips_triprequireddocumentitem_pkey;
                    ALTER TABLE trips_trippreparation DROP CONSTRAINT trips_trippreparation_pkey;

                    ALTER TABLE trips_tripheadsupinfoitem DROP COLUMN id;
                    ALTER TABLE trips_trippreparationpackingitem DROP COLUMN id;
                    ALTER TABLE trips_triprequireddocumentitem DROP COLUMN id;
                    ALTER TABLE trips_trippreparation DROP COLUMN id;

                    ALTER TABLE trips_trippreparation RENAME COLUMN id_uuid TO id;
                    ALTER TABLE trips_tripheadsupinfoitem RENAME COLUMN id_uuid TO id;
                    ALTER TABLE trips_trippreparationpackingitem RENAME COLUMN id_uuid TO id;
                    ALTER TABLE trips_triprequireddocumentitem RENAME COLUMN id_uuid TO id;

                    ALTER TABLE trips_tripheadsupinfoitem RENAME COLUMN preparation_uuid TO preparation_id;
                    ALTER TABLE trips_trippreparationpackingitem RENAME COLUMN preparation_uuid TO preparation_id;
                    ALTER TABLE trips_triprequireddocumentitem RENAME COLUMN preparation_uuid TO preparation_id;

                    ALTER TABLE trips_trippreparation DROP CONSTRAINT IF EXISTS trips_trippreparation_pkey;
                    ALTER TABLE trips_tripheadsupinfoitem DROP CONSTRAINT IF EXISTS trips_tripheadsupinfoitem_pkey;
                    ALTER TABLE trips_trippreparationpackingitem DROP CONSTRAINT IF EXISTS trips_trippreparationpackingitem_pkey;
                    ALTER TABLE trips_triprequireddocumentitem DROP CONSTRAINT IF EXISTS trips_triprequireddocumentitem_pkey;

                    ALTER TABLE trips_trippreparation ADD CONSTRAINT trips_trippreparation_pkey PRIMARY KEY (id);
                    ALTER TABLE trips_tripheadsupinfoitem ADD CONSTRAINT trips_tripheadsupinfoitem_pkey PRIMARY KEY (id);
                    ALTER TABLE trips_trippreparationpackingitem ADD CONSTRAINT trips_trippreparationpackingitem_pkey PRIMARY KEY (id);
                    ALTER TABLE trips_triprequireddocumentitem ADD CONSTRAINT trips_triprequireddocumentitem_pkey PRIMARY KEY (id);

                    ALTER TABLE trips_tripheadsupinfoitem DROP CONSTRAINT IF EXISTS trips_heads_up_preparation_fk;
                    ALTER TABLE trips_trippreparationpackingitem DROP CONSTRAINT IF EXISTS trips_packing_item_preparation_fk;
                    ALTER TABLE trips_triprequireddocumentitem DROP CONSTRAINT IF EXISTS trips_required_document_preparation_fk;

                    ALTER TABLE trips_tripheadsupinfoitem DROP CONSTRAINT IF EXISTS unique_heads_up_info_order;
                    ALTER TABLE trips_trippreparationpackingitem DROP CONSTRAINT IF EXISTS unique_packing_item_order;
                    ALTER TABLE trips_triprequireddocumentitem DROP CONSTRAINT IF EXISTS unique_required_document_order;

                    DROP INDEX IF EXISTS trips_triph_prepara_f1d11a_idx;
                    DROP INDEX IF EXISTS trips_tripp_prepara_04573e_idx;
                    DROP INDEX IF EXISTS trips_tripr_prepara_cab8e3_idx;

                    CREATE INDEX IF NOT EXISTS trips_triph_prepara_f1d11a_idx
                    ON trips_tripheadsupinfoitem (preparation_id, sort_order);
                    CREATE INDEX IF NOT EXISTS trips_tripp_prepara_04573e_idx
                    ON trips_trippreparationpackingitem (preparation_id, sort_order);
                    CREATE INDEX IF NOT EXISTS trips_tripr_prepara_cab8e3_idx
                    ON trips_triprequireddocumentitem (preparation_id, sort_order);
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=r"""

                    WITH ordered_rows AS (
                        SELECT id, row_number() OVER (
                            PARTITION BY preparation_id
                            ORDER BY sort_order, id
                        ) AS normalized_sort_order
                        FROM trips_tripheadsupinfoitem
                    )
                    UPDATE trips_tripheadsupinfoitem item
                    SET sort_order = ordered_rows.normalized_sort_order
                    FROM ordered_rows
                    WHERE item.id = ordered_rows.id;

                    WITH ordered_rows AS (
                        SELECT id, row_number() OVER (
                            PARTITION BY preparation_id
                            ORDER BY sort_order, id
                        ) AS normalized_sort_order
                        FROM trips_trippreparationpackingitem
                    )
                    UPDATE trips_trippreparationpackingitem item
                    SET sort_order = ordered_rows.normalized_sort_order
                    FROM ordered_rows
                    WHERE item.id = ordered_rows.id;

                    WITH ordered_rows AS (
                        SELECT id, row_number() OVER (
                            PARTITION BY preparation_id
                            ORDER BY sort_order, id
                        ) AS normalized_sort_order
                        FROM trips_triprequireddocumentitem
                    )
                    UPDATE trips_triprequireddocumentitem item
                    SET sort_order = ordered_rows.normalized_sort_order
                    FROM ordered_rows
                    WHERE item.id = ordered_rows.id;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=r"""

                    ALTER TABLE trips_tripheadsupinfoitem
                    ADD CONSTRAINT unique_heads_up_info_order UNIQUE (preparation_id, sort_order);
                    ALTER TABLE trips_trippreparationpackingitem
                    ADD CONSTRAINT unique_packing_item_order UNIQUE (preparation_id, sort_order);
                    ALTER TABLE trips_triprequireddocumentitem
                    ADD CONSTRAINT unique_required_document_order UNIQUE (preparation_id, sort_order);

                    ALTER TABLE trips_tripheadsupinfoitem
                    ADD CONSTRAINT trips_heads_up_preparation_fk
                    FOREIGN KEY (preparation_id) REFERENCES trips_trippreparation(id) DEFERRABLE INITIALLY DEFERRED;

                    ALTER TABLE trips_trippreparationpackingitem
                    ADD CONSTRAINT trips_packing_item_preparation_fk
                    FOREIGN KEY (preparation_id) REFERENCES trips_trippreparation(id) DEFERRABLE INITIALLY DEFERRED;

                    ALTER TABLE trips_triprequireddocumentitem
                    ADD CONSTRAINT trips_required_document_preparation_fk
                    FOREIGN KEY (preparation_id) REFERENCES trips_trippreparation(id) DEFERRABLE INITIALLY DEFERRED;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='tripheadsupinfoitem',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='trippreparation',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='trippreparationpackingitem',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='triprequireddocumentitem',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
