# Generated by Django 5.1.7 on 2026-07-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_tripheadsupinfoitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippreparationpackingitem',
            name='is_packed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
