# Generated by Codex on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0012_trippreparationpackingitem_is_packed"),
    ]

    operations = [
        migrations.AddField(
            model_name="triprequireddocumentitem",
            name="document_file_name",
            field=models.CharField(blank=True, default="", max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="triprequireddocumentitem",
            name="document_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
