# Generated by Django 5.1.7 on 2026-07-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_triprequireddocumentitem_document_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='completed_stats_recorded',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
