# Generated by Codex on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0014_trip_completed_stats_recorded"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tripagentmessage",
            name="unique_trip_agent_message_sequence",
        ),
        migrations.RemoveIndex(
            model_name="tripagentmessage",
            name="trips_tripa_trip_id_be9103_idx",
        ),
        migrations.RenameField(
            model_name="tripagentmessage",
            old_name="payload",
            new_name="metadata",
        ),
        migrations.RemoveField(
            model_name="tripagentmessage",
            name="sequence",
        ),
        migrations.RemoveField(
            model_name="tripagentmessage",
            name="step",
        ),
        migrations.RemoveField(
            model_name="tripagentmessage",
            name="trip",
        ),
        migrations.AlterField(
            model_name="tripagentmessage",
            name="sender",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("agent", "Agent"),
                    ("system", "System"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterModelOptions(
            name="tripagentmessage",
            options={"ordering": ["created_at"]},
        ),
    ]
