# Generated by Django 5.1.7 on 2026-07-19 03:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_update_trip_agent_message_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tripagentconversationsession',
            name='trips_tripa_trip_id_5c7bdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='trippreparation',
            name='trips_tripp_trip_id_660ede_idx',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='agent_context',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='tripitinerary',
            old_name='session_id',
            new_name='external_session_id',
        ),
        migrations.RenameField(
            model_name='trippreparation',
            old_name='session_id',
            new_name='external_session_id',
        ),
        migrations.RenameField(
            model_name='triprecommendations',
            old_name='session_id',
            new_name='external_session_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='accommodation_preference',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='agent_active_failed_message',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='total_budget',
        ),
        migrations.RenameField(
            model_name='tripagentconversationsession',
            old_name='current_step',
            new_name='step',
        ),
        migrations.RemoveField(
            model_name='tripagentconversationsession',
            name='qna_count',
        ),
        migrations.RemoveField(
            model_name='tripitinerary',
            name='is_finalized',
        ),
        migrations.RemoveField(
            model_name='trippreparation',
            name='is_finalized',
        ),
        migrations.RemoveField(
            model_name='triprecommendations',
            name='is_finalized',
        ),
        migrations.AddField(
            model_name='tripactivityrecommendationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripactivityrecommendationitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripactivityrecommendationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tripactivityrecommendationitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripattractionrecommendationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripattractionrecommendationitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripattractionrecommendationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tripattractionrecommendationitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripcuisinerecommendationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripcuisinerecommendationitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripcuisinerecommendationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tripcuisinerecommendationitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripitinerary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripitinerary',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triprecommendations',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triprecommendations',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_step',
            field=models.CharField(choices=[('preference', 'Preference'), ('recommendation', 'Recommendation'), ('itinerary', 'Itinerary'), ('preparation', 'Preparation'), ('overview', 'Overview'), ('completed', 'Completed')], db_index=True, default='preference', max_length=32),
        ),
        migrations.AlterField(
            model_name='tripagentconversationsession',
            name='step',
            field=models.CharField(choices=[('preference', 'Preference'), ('recommendation', 'Recommendation'), ('itinerary', 'Itinerary'), ('preparation', 'Preparation'), ('overview', 'Overview'), ('completed', 'Completed')], db_index=True, default='preference', max_length=32),
        ),
    ]
