# Generated by Django 5.1.7 on 2026-07-23 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_add_trip_agent_session_step_index'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=r"""
                    /*
                     * PostgreSQL cannot cast bigint primary keys to UUIDs directly.
                     * Preserve existing rows by deriving stable UUIDs from the old
                     * table name and integer value. Foreign-key values use the same
                     * derivation as the primary key they reference.
                     *
                     * Save and temporarily remove every FK that references either
                     * converted parent table. Reusing pg_get_constraintdef keeps
                     * the original constraint names and deferrability.
                     */
                    CREATE TEMPORARY TABLE trips_0019_saved_foreign_keys
                    ON COMMIT DROP
                    AS
                    SELECT
                        conrelid::regclass::text AS table_name,
                        conname AS constraint_name,
                        pg_get_constraintdef(oid) AS constraint_definition
                    FROM pg_constraint
                    WHERE contype = 'f'
                      AND confrelid IN (
                          'trips_tripitinerary'::regclass,
                          'trips_triprecommendations'::regclass
                      );

                    DO $$
                    DECLARE
                        saved_constraint record;
                    BEGIN
                        FOR saved_constraint IN
                            SELECT table_name, constraint_name
                            FROM trips_0019_saved_foreign_keys
                        LOOP
                            EXECUTE format(
                                'ALTER TABLE %s DROP CONSTRAINT %I',
                                saved_constraint.table_name,
                                saved_constraint.constraint_name
                            );
                        END LOOP;
                    END $$;

                    /*
                     * BigAutoField is backed by an identity (or a sequence default
                     * on older PostgreSQL/Django combinations). UUID values are
                     * generated by the model after this migration, so remove the
                     * database-side integer generators before changing the type.
                     */
                    ALTER TABLE trips_tripactivityrecommendationitem
                        ALTER COLUMN id DROP IDENTITY IF EXISTS,
                        ALTER COLUMN id DROP DEFAULT;
                    ALTER TABLE trips_tripattractionrecommendationitem
                        ALTER COLUMN id DROP IDENTITY IF EXISTS,
                        ALTER COLUMN id DROP DEFAULT;
                    ALTER TABLE trips_tripcuisinerecommendationitem
                        ALTER COLUMN id DROP IDENTITY IF EXISTS,
                        ALTER COLUMN id DROP DEFAULT;
                    ALTER TABLE trips_tripitinerary
                        ALTER COLUMN id DROP IDENTITY IF EXISTS,
                        ALTER COLUMN id DROP DEFAULT;
                    ALTER TABLE trips_triprecommendations
                        ALTER COLUMN id DROP IDENTITY IF EXISTS,
                        ALTER COLUMN id DROP DEFAULT;

                    ALTER TABLE trips_tripactivityrecommendationitem
                        ALTER COLUMN id TYPE uuid
                        USING md5(
                            'trips_tripactivityrecommendationitem:' || id::text
                        )::uuid;

                    ALTER TABLE trips_tripattractionrecommendationitem
                        ALTER COLUMN id TYPE uuid
                        USING md5(
                            'trips_tripattractionrecommendationitem:' || id::text
                        )::uuid;

                    ALTER TABLE trips_tripcuisinerecommendationitem
                        ALTER COLUMN id TYPE uuid
                        USING md5(
                            'trips_tripcuisinerecommendationitem:' || id::text
                        )::uuid;

                    ALTER TABLE trips_tripitinerary
                        ALTER COLUMN id TYPE uuid
                        USING md5('trips_tripitinerary:' || id::text)::uuid;

                    ALTER TABLE trips_tripitinerarybudget
                        ALTER COLUMN itinerary_id TYPE uuid
                        USING md5(
                            'trips_tripitinerary:' || itinerary_id::text
                        )::uuid;

                    ALTER TABLE trips_tripitineraryday
                        ALTER COLUMN itinerary_id TYPE uuid
                        USING md5(
                            'trips_tripitinerary:' || itinerary_id::text
                        )::uuid;

                    ALTER TABLE trips_triprouteplanitem
                        ALTER COLUMN itinerary_id TYPE uuid
                        USING md5(
                            'trips_tripitinerary:' || itinerary_id::text
                        )::uuid;

                    ALTER TABLE trips_triprecommendations
                        ALTER COLUMN id TYPE uuid
                        USING md5('trips_triprecommendations:' || id::text)::uuid;

                    ALTER TABLE trips_tripactivityrecommendationitem
                        ALTER COLUMN recommendation_id TYPE uuid
                        USING md5(
                            'trips_triprecommendations:' || recommendation_id::text
                        )::uuid;

                    ALTER TABLE trips_tripattractionrecommendationitem
                        ALTER COLUMN recommendation_id TYPE uuid
                        USING md5(
                            'trips_triprecommendations:' || recommendation_id::text
                        )::uuid;

                    ALTER TABLE trips_tripcuisinerecommendationitem
                        ALTER COLUMN recommendation_id TYPE uuid
                        USING md5(
                            'trips_triprecommendations:' || recommendation_id::text
                        )::uuid;

                    DO $$
                    DECLARE
                        saved_constraint record;
                    BEGIN
                        FOR saved_constraint IN
                            SELECT
                                table_name,
                                constraint_name,
                                constraint_definition
                            FROM trips_0019_saved_foreign_keys
                        LOOP
                            EXECUTE format(
                                'ALTER TABLE %s ADD CONSTRAINT %I %s',
                                saved_constraint.table_name,
                                saved_constraint.constraint_name,
                                saved_constraint.constraint_definition
                            );
                        END LOOP;
                    END $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='tripactivityrecommendationitem',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='tripattractionrecommendationitem',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='tripcuisinerecommendationitem',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='tripitinerary',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='triprecommendations',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='tripagentconversationsession',
            name='step',
            field=models.CharField(choices=[('preference', 'Preference'), ('recommendation', 'Recommendation'), ('itinerary', 'Itinerary'), ('preparation', 'Preparation'), ('overview', 'Overview'), ('completed', 'Completed')], db_index=True, max_length=32),
        ),
    ]
