# Generated by Django 5.1.7 on 2026-07-28 05:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def organize_existing_sessions(apps, schema_editor):
    Trip = apps.get_model("trips", "Trip")
    PlanningSession = apps.get_model("trips", "TripPlanningSession")
    StepSession = apps.get_model("trips", "TripAgentConversationSession")
    PlanningMessage = apps.get_model("trips", "TripAgentMessage")
    ConversationSession = apps.get_model("trips", "TripConversationSession")
    ConversationMessage = apps.get_model("trips", "TripConversationMessage")

    for trip in Trip.objects.all().iterator():
        planning_session, _ = PlanningSession.objects.get_or_create(
            trip_id=trip.id,
            defaults={
                "user_id": trip.user_id,
                "created_by_id": trip.created_by_id,
                "updated_by_id": trip.updated_by_id,
            },
        )
        conversation_session, _ = ConversationSession.objects.get_or_create(
            trip_id=trip.id,
            defaults={
                "user_id": trip.user_id,
                "is_active": trip.status in {"ready", "in_progress", "completed"},
                "created_by_id": trip.created_by_id,
                "updated_by_id": trip.updated_by_id,
            },
        )

        planning_step_sessions = []
        legacy_sessions = StepSession.objects.filter(trip_id=trip.id).order_by(
            "step", "-updated_at"
        )
        for legacy_session in legacy_sessions:
            metadata = legacy_session.metadata or {}
            if metadata.get("source") == "trip_chat":
                for message in PlanningMessage.objects.filter(session_id=legacy_session.id):
                    copied = ConversationMessage.objects.create(
                        id=message.id,
                        session_id=conversation_session.id,
                        sender=message.sender,
                        content=message.content,
                        metadata=message.metadata,
                        created_by_id=message.created_by_id,
                        updated_by_id=message.updated_by_id,
                    )
                    ConversationMessage.objects.filter(pk=copied.pk).update(
                        created_at=message.created_at,
                        updated_at=message.updated_at,
                    )
                legacy_session.delete()
            else:
                planning_step_sessions.append(legacy_session)

        canonical_by_step = {}
        for step_session in planning_step_sessions:
            canonical = canonical_by_step.get(step_session.step)
            if canonical is None:
                step_session.planning_session_id = planning_session.id
                step_session.user_id = trip.user_id
                step_session.save(update_fields=["planning_session", "user"])
                canonical_by_step[step_session.step] = step_session
                continue

            PlanningMessage.objects.filter(session_id=step_session.id).update(
                session_id=canonical.id
            )
            step_session.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_alter_tripactivityrecommendationitem_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_session_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_session', to='trips.trip')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_conversation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TripConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trips.tripconversationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPlanningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planning_session', to='trips.trip')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_planning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='tripagentconversationsession',
            name='planning_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_sessions', to='trips.tripplanningsession'),
        ),
        migrations.RunPython(organize_existing_sessions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tripagentconversationsession',
            name='planning_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_sessions', to='trips.tripplanningsession'),
        ),
        migrations.AddConstraint(
            model_name='tripagentconversationsession',
            constraint=models.UniqueConstraint(fields=('planning_session', 'step'), name='unique_trip_planning_step_session'),
        ),
        migrations.AddIndex(
            model_name='tripconversationsession',
            index=models.Index(fields=['user', 'is_active'], name='trips_tripc_user_id_577d92_idx'),
        ),
        migrations.AddIndex(
            model_name='tripconversationmessage',
            index=models.Index(fields=['session', 'sender'], name='trips_tripc_session_088ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='tripplanningsession',
            index=models.Index(fields=['user', 'is_active'], name='trips_tripp_user_id_afee45_idx'),
        ),
    ]
