# Generated by Django 5.1.7 on 2026-08-04 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('trips', '0020_planning_and_conversation_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTripNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('packing_reminder', 'Packing and documents reminder'), ('daily_summary', 'Daily trip summary'), ('daily_check_in', 'Daily check-in')], max_length=32)),
                ('delivery_type', models.CharField(choices=[('alert', 'Alert'), ('message', 'Message')], max_length=10)),
                ('scheduled_for', models.DateTimeField()),
                ('local_date', models.DateField()),
                ('local_time', models.TimeField()),
                ('timezone', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_trip_events', to='notification.notification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_trip_events', to='trips.tripconversationmessage')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='trips.trip')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='scheduled_due_idx'), models.Index(fields=['trip', 'delivery_type', 'status'], name='scheduled_trip_delivery_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('delivery_type', 'alert'), ('message__isnull', True)), models.Q(('alert__isnull', True), ('delivery_type', 'message')), _connector='OR'), name='scheduled_event_matches_delivery')],
            },
        ),
    ]
