# Generated by Django 5.1.7 on 2026-08-04 16:25

from django.conf import settings
from django.db import migrations, models


def mark_existing_non_scheduled_messages_read(apps, schema_editor):
    message_model = apps.get_model("trips", "TripConversationMessage")
    message_model.objects.filter(read_at__isnull=True).exclude(
        metadata__has_key="scheduled_event_id"
    ).update(read_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_scheduledtripnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tripconversationmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(
            mark_existing_non_scheduled_messages_read,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='tripconversationmessage',
            index=models.Index(fields=['session', 'sender', 'read_at'], name='trips_tripc_session_79c870_idx'),
        ),
    ]
