# Generated by Django 5.1.7 on 2026-08-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_tripconversationmessage_read_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtripnotification',
            name='event_type',
            field=models.CharField(choices=[('packing_reminder', 'Packing and documents reminder'), ('daily_summary', 'Daily trip summary'), ('daily_check_in', 'Daily check-in'), ('trip_started', 'Trip started'), ('trip_completed', 'Trip completed')], max_length=32),
        ),
    ]
