# Generated by Django 5.1.7 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0024_rename_payload_scheduledtripnotification_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="triprequireddocumentitem",
            name="is_packed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
